version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "frontend deps"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "backend deps"
    labels:
      - "dependencies"
      - "backend"
